from dataclasses import dataclass

# Bump when `build_prompt` changes so cached explanations generated by an older
# prompt are not served for the rest of their TTL (the cache key includes this).
EXPLANATION_PROMPT_VERSION = 2


@dataclass(frozen=True)
class ExplanationPrompt:
    """The two-part instruction handed to an LLM to explain a question.

    Framework-free on purpose: the domain decides *what* the model is asked,
    while the infrastructure adapter maps this to a concrete provider's message
    format.
    """

    system: str
    user: str


@dataclass(frozen=True)
class ExplainableQuestion:
    """A question with its answer, ready to be explained to a student."""

    question_id: int
    text: str
    options: list[str]
    correct_answer: str

    def build_prompt(self) -> ExplanationPrompt:
        numbered = "\n".join(
            f"{index}. {option}" for index, option in enumerate(self.options, start=1)
        )
        system = (
            "You are a patient tutor helping a student who may be seeing this "
            "topic for the first time and might not understand why the correct "
            "answer is right. Explain the whole question from the ground up so a "
            "complete beginner can follow. Cover all of the following:\n"
            "1. What the question is asking, and what every key term, concept, or "
            "symbol in it means — define any jargon in simple, everyday words.\n"
            "2. Go through each answer option one by one: explain what it means "
            "and why it is correct or incorrect.\n"
            "3. Explain the reasoning that makes the correct answer right, step by "
            "step, and add a short simple example if it helps understanding.\n"
            "Assume no prior knowledge. Be accurate, clear, and encouraging. "
            "Respond in the same language as the question. Write in plain prose "
            "with short paragraphs or line breaks between points; do not use "
            "Markdown formatting or headings. If you include any mathematical "
            "notation, wrap it in $ … $ so it renders correctly."
        )
        user = (
            f"Question:\n{self.text}\n\n"
            f"Options:\n{numbered}\n\n"
            f"The correct answer is: {self.correct_answer}\n\n"
            "Explain everything in this question and its answers at a basic level "
            "so I understand what each part means and why this answer is correct."
        )
        return ExplanationPrompt(system=system, user=user)
